server:
  port: 9080
  
spring:
  application:
      name: Microservicio-PruebaTecnica
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prueba_tecnica
    username: root
    password: 1234
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect